In [1]:
import numpy as np

In [2]:
import pickle

rede_neural = pickle.load(open('rede_neural_trained.sav', 'rb'))
arvore = pickle.load(open('arvore_trained.sav', 'rb'))
svm = pickle.load(open('svm_trained.sav', 'rb'))

In [3]:
import pickle

with open('credit.pkl', 'rb') as f:
    X_credit_treinamento, Y_credit_treinamento, X_credit_teste, Y_credit_teste = pickle.load(f)

In [4]:
# Concatenate
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
Y_credit = np.concatenate((Y_credit_treinamento, Y_credit_teste), axis = 0)

In [5]:
novo_registro = X_credit[0]
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

In [6]:
novo_registro.shape

(3,)

In [14]:
novo_registro = novo_registro.reshape(1, -1)

In [8]:
novo_registro

array([[-1.3754462 ,  0.50631087,  0.10980934]])

In [9]:
rede_neural.predict(novo_registro)

array([0])

In [10]:
arvore.predict(novo_registro)

array([0])

In [11]:
svm.predict(novo_registro)

array([0])

# Combinação de classificadores

In [12]:
novo_registro = X_credit[0]

In [15]:
resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [16]:
resposta_rede_neural[0], resposta_arvore[0], resposta_svm[0]

(array([0]), array([0]), array([0]))

In [17]:
paga = 0
nao_paga = 0

if resposta_rede_neural[0] == 1:
    nao_paga += 1
else:
    paga += 1

if resposta_arvore[0] == 1:
    nao_paga += 1
else:
    paga += 1
    
if resposta_svm[0] == 1:
    nao_paga += 1
else:
    paga += 1
    
if paga > nao_paga:
    print('Cliente paga')
    
elif paga == nao_paga:
    print('Empate')
else:
    print('Cliente nao paga')

Cliente paga


# Rejeição de classificadores

In [18]:
probabilidade_rede_neural = rede_neural.predict_proba(novo_registro)
probabilidade_rede_neural

array([[1.0000000e+00, 8.3163469e-17]])

In [19]:
confianca_rede_neural = probabilidade_rede_neural.max()
confianca_rede_neural

np.float64(0.9999999999999999)

In [20]:
probabilidade_arvore = arvore.predict_proba(novo_registro)
probabilidade_arvore

array([[1., 0.]])

In [21]:
confianca_arvore = probabilidade_arvore.max()
confianca_arvore

np.float64(1.0)