In [6]:
import numpy as np

In [7]:
import pickle

rede_neural = pickle.load(open('rede_neural_trained.sav', 'rb'))
arvore = pickle.load(open('arvore_trained.sav', 'rb'))
svm = pickle.load(open('svm_trained.sav', 'rb'))

In [8]:
import pickle

with open('credit.pkl', 'rb') as f:
    X_credit_treinamento, Y_credit_treinamento, X_credit_teste, Y_credit_teste = pickle.load(f)

In [9]:
# Concatenate
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
Y_credit = np.concatenate((Y_credit_treinamento, Y_credit_teste), axis = 0)

In [10]:
novo_registro = X_credit[0]
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

In [11]:
novo_registro.shape

(3,)

In [12]:
novo_registro = novo_registro.reshape(1, -1)

In [13]:
novo_registro

array([[-1.3754462 ,  0.50631087,  0.10980934]])

In [14]:
rede_neural.predict(novo_registro)

array([0])

In [15]:
arvore.predict(novo_registro)

array([0])

In [16]:
svm.predict(novo_registro)

array([0])